# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ProgramacaoAplicadaGrupo4
                                 A QGIS plugin
 Solução do Grupo 4
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-03-25
        copyright            : (C) 2024 by Grupo 4
        email                : alexprocopio323@ime.eb.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Grupo 4'
__date__ = '2024-03-25'
__copyright__ = '(C) 2024 by Grupo 4'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ProgramacaoAplicadaGrupo4 class from file ProgramacaoAplicadaGrupo4.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .programacao_aplicada_grupo_4 import ProgramacaoAplicadaGrupo4Plugin
    return ProgramacaoAplicadaGrupo4Plugin()
